#!/bin/bash

# custom certificate authority path
CA_CERTIFICATES_PATH=/home/appuser/certs/ca.crt
LOCAL_CA_PATH="/usr/local/share/ca-certificates/ca.crt"

update_ca() {
  echo "Updating CA certificates..."
  cp "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}"
  update-ca-certificates --fresh >/dev/null
}

if [ -f "${CA_CERTIFICATES_PATH}" ]; then
  # update the ca if the custom ca is different than the current
  cmp --silent "${CA_CERTIFICATES_PATH}" "${LOCAL_CA_PATH}" || update_ca
fi

chown -R appuser:appuser /home/appuser  

# Drop privileges to 'appuser' before executing the main application  
exec su -s /bin/bash -c "exec $*" appuser
